server.port=8088
spring.application.name=api
server.forward-headers-strategy=framework
springdoc.swagger-ui.server.url=${SPRING_DOC_SERVER_URL}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# KEYCLOAK CONFIGS
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWT_CERT_URL}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL}

# REDIS CONFIG
spring.data.redis.host=${CS_REDIS_HOST}
spring.data.redis.port=${CS_REDIS_PORT}
rate.limiting.enabled=${RATE_LIMITING_ENABLED}
rate.limiting.ttl=${RATE_LIMITING_TTL}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

logging.file.name=/tmp/logs/api.log

spring.boot.admin.client.url=${SPRING_BOOT_ADMIN_CLIENT_URL}
spring.boot.admin.client.username=${ADMIN_USERNAME}
spring.boot.admin.client.password=${ADMIN_PASSWORD}

spring.security.user.name=${ACTUATOR_USERNAME}
spring.security.user.password=${ACTUATOR_PASSWORD}
spring.boot.admin.client.instance.metadata.user.name=${ACTUATOR_USERNAME}
spring.boot.admin.client.instance.metadata.user.password=${ACTUATOR_PASSWORD}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
