version: '3.5'

services:
  cs-api:
    build: ../
    image: pnthusi/cs-api:latest
    ports:
      - "8077:8088"
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
      KEYCLOAK_JWT_CERT_URL: ${KEYCLOAK_JWT_CERT_URL}
      KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      SPRING_DOC_SERVER_URL: ${SPRING_DOC_SERVER_URL}

