version: '3.5'

services:
  api:
    build: ../api/
    image: kenyahmis/cs-api:latest
    ports:
      - "${API_PORT:-8099}:8088"
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
      KEYCLOAK_JWT_CERT_URL: ${KEYCLOAK_JWT_CERT_URL}
#      KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      SPRING_DOC_SERVER_URL: ${SPRING_DOC_SERVER_URL}
      CS_REDIS_HOST: ${CS_REDIS_HOST}
      CS_REDIS_PORT: ${CS_REDIS_PORT}
      TZ: Africa/Nairobi
  worker:
    build: ../worker/
    image: kenyahmis/cs-worker:latest
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Africa/Nairobi
  cs_redis:
    image: redis:7
    restart: unless-stopped
    environment:
      TZ: Africa/Nairobi
  kafka:
    image: bitnami/kafka:3.4.1
#    user: root
    restart: unless-stopped
    environment:
      BITNAMI_DEBUG: 'true'
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      TZ: Africa/Nairobi
    volumes:
      - kafka_data:/bitnami/kafka
volumes:
  kafka_data:

